EXTRA_CFLAGS += -Iarch/arm/mach-msm -Iarch/arm/tools

obj-$(CONFIG_MACH_MSM7X25A_E0EU) += board-msm7x27a_e0.o
obj-$(CONFIG_MACH_MSM7X25A_E0EU) += board-msm7x27a-regulator_e0.o
#obj-$(CONFIG_MACH_MSM7X25A_E0EU) += board-msm7x27a-sound_e0.o
#obj-$(CONFIG_MACH_MSM7X25A_E0EU) += board-msm7627a-bt_e0.o
#obj-$(CONFIG_MACH_MSM7X25A_E0EU) += board-msm7627a-camera_e0.o
#obj-$(CONFIG_MACH_MSM7X25A_E0EU) += board-msm7627a-io_e0.o
#obj-$(CONFIG_MACH_MSM7X25A_E0EU) += board-msm7627a-storage_e0.o
#obj-$(CONFIG_MACH_MSM7X25A_E0EU) += board-msm7627a-wlan_e0.o
#obj-$(CONFIG_MACH_MSM7X25A_E0EU) += board-msm7627a-display_e0.o
